version: '3.9'
services:
  cucumber-service:
    build:
      context: ./src/main/docker/
      dockerfile: Dockerfile.legacy-jar
    image: quarkus/cucumber-garden-quarkus-legacy-jar
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/cucumber
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: admin
      LANGUAGE: en_US:en
      JAVA_OPTS_APPEND: -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
      JAVA_APP_JAR: /deployments/quarkus-run.jar
    ports:
      - '8080:8080'
    networks:
      - cucumber_network

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - '5433:5432' # This port mapping is only required for testing the database connection with PSQL from the host machine. 
                    # The application running inside the Docker network will still function properly without this mapping, 
                    # as it communicates with the database using the internal Docker network and the service name 'postgres'.
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cucumber
    volumes:
      - ./src/main/resources/sql-scripts/data.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - cucumber_network

networks:
 cucumber_network:
#    external: true
#    name: host

#networks:
#  network1:
#    name: my-network
#    attachable: true
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.17.0.0/16
#          ip_range: 172.17.5.0/24
#          gateway: 172.17.1.1